#!/bin/bash
echo "===================="
echo "|     LWServer     |"
echo "===================="
echo "                    "
echo " ogwhisper/lwserver "
echo "                    "
echo "===================="
echo "|   Maintenance:   |"
echo "===================="
echo "                    "
echo "    Whisper#7076    "
echo "                    "
echo "===================="
echo "|  sampollard.dev  |"
echo "===================="
echo ""
echo ""
echo ""